### ISSUE TITLE
Problem on running HAWK 0.9.8 beta: on the EIG6.0.1-Hawk/bin/smartpca step

### ISSUE THREAD

**Issue by leoisl** [atifrahman/HAWK#1]
Hello,

I am trying to run HAWK 0.9.8 beta (downloaded from [http://atifrahman.github.io/HAWK/](http://atifrahman.github.io/HAWK/)) on bacterial strains where I do not have a reference genome. I managed to run [HAWK 0.8.3 Beta](https://github.com/atifrahman/HAWK/releases/tag/0.8.3) on these strains, but I can't do it for the new HAWK version associated with the publication [https://elifesciences.org/articles/32920](https://elifesciences.org/articles/32920). I am blocked when running `EIG6.0.1-Hawk/bin/smartpca -V -p <hawk_dir>/parfile.txt`. The main problem is that `smartpca` takes 3 input files:
```
genotypename: gwas_eigenstratX.geno
snpname: gwas_eigenstratX.snp
indivname: gwas_eigenstratX.ind
```
but the previous steps (k-mer counting with script `supplements/countKmers` and the lines before invoking `smartpca` in script `supplements/runHawk`) did not produce `gwas_eigenstratX.geno` and `gwas_eigenstratX.snp`, but only `gwas_eigenstratX.ind`. Since these files do not exist, `smartpca` fails, and since these 3 input files are required, I do not manage to run them. I also did not find any documentation on this regard.

Could you point me any direction on how to solve this?

Thank you in advance.

**Comment by atifrahman** [comment]
Did you update hawkDir correctly to run the latest version of hawk (0.9.8)? The new version should generate gwas_eigenstratX.geno and gwas_eigenstratX.snp. Lines 621 to 642 here
https://github.com/atifrahman/HAWK/blob/master/hawk.cpp

**Comment by leoisl** [comment]
Hello,

Thanks for the fast and detailed answer. Hawk is running ok, the problem was on my end, I had a mistake in my runHawk shell script. Sorry about this, thank you again for the answer.
