### ISSUE TITLE
Jellyfish install and SureSelect

### ISSUE THREAD

**Issue by jckhearn** [atifrahman/HAWK#10]
Hello,
I have two questions relating to HAWK.

1. I have been having difficulty installing the included version of jellyfish, specifically:

`./jellyfish/err.hpp:98:39: error: throw will always call terminate() [-Werror=terminate]`

I have tried different versions of compiler to no avail. However, installing the latest version of non-HAWK jellyfish is fine. What are the disadvantages of not using the included jellyfish?

2. I have SureSelect data for a large number of genes and regions in our study organims, and we are especially interested in CNVs between case and controls. Are there any reasons for not using HAWK to look for associations because of this? 

Best wishes,
Jack

**Comment by jckhearn** [comment]
I have switched off `-Werror` during compilation, however I am now getting the:

`terminate called after throwing an instance of 'SquareBinaryMatrix::SingularMatrix'`

error of issue #2. However, applying the patch fails:

`patching file jellyfish/dump_main.cc`
`Hunk #1 FAILED at 38.`
`1 out of 1 hunk FAILED -- saving rejects to file jellyfish/dump_main.cc.rej`

Thanks

**Comment by atifrahman** [comment]
Sorry about the problems you're facing. Can you please give me the link of the Jellyfish version you're applying the patch on?

And HAWK is able to map associations to CNVs given enough samples.

**Comment by jckhearn** [comment]
It's failing in HAWK version 0.9.8. Just doubled checked with a fresh install, and I'm getting the same error. I am installing after git cloning HAWK.

Thanks,
Jack

**Comment by atifrahman** [comment]
I meant what is the version of Jellyfish, you're trying to apply the patch on? 

You need to either install the version provided with HAWK (https://github.com/atifrahman/HAWK/blob/master/supplements/jellyfish-Hawk.tar.gz) or download the latest version (https://github.com/gmarcais/Jellyfish), apply the patch (https://github.com/atifrahman/HAWK/blob/master/supplements/dump_numeric.patch) and install.

**Comment by jckhearn** [comment]
I was applying the patch to jellyfish 1.1.6 included with HAWK 0.9.8. 

I have jellyfish 2.2.10, and this works fine. Are there any disadvantages to kmer counting with this unmodified version versus the one included with HAWK?

**Comment by atifrahman** [comment]
It actually needs to be modified to output integer representations of the k-mers instead of strings to work with HAWK. The patch does this modification.

**Comment by standage** [comment]
Hi there! I am getting the same SingularMatrix error with any attempt to run HAWK. I downloaded the latest version of HAWK this morning from Github, and installed the version of Jellyfish bundled with the HAWK source code distribution.

**Comment by standage** [comment]
Using Jellyfish v2 seems to work fine, as suggested in other issue threads.

Proposed an update to the documentation in #11.

**EDIT**: I was mistaken, Jellyfish 2 did not work. I ended up downloading the latest version of Jellyfish 1 and editing it manually (the supplied patch didn't work for some reason).

**Comment by jckhearn** [comment]
I have this working now with jellyfish v1.1.12 (https://github.com/gmarcais/Jellyfish/releases) by applying the patch and then installing. Output looks like this for the first 10 lines:

`0 82`
`192 2`
`768 2`
`3072 3`
`6193 2`
`12288 3`
`24773 2`
`49152 3`
`62287 2`
`99092 2`

Assume the same works for jellyfish v2, so will try that as well.

**Comment by atifrahman** [comment]
Great! We are working on a few things including testing with Jellyfish 2. We hope to post an update soon.
