### ISSUE TITLE
sorted_files.txt incorrect

### ISSUE THREAD

**Issue by dstern** [atifrahman/HAWK#13]
After running countKmers, I found that the file sorted_files.txt had incorrect specification of the sample folders.
The sample folders were indicated as Reads_catrim.Hcor_SM05L02_Red.fastq.gz, etc.
The sorted_files.txt included lines like so
/Hcor/Reads_Reads_catrim.Hcor_SM05L02_Red.fastq.gz/Reads_catrim.Hcor_SM05L02_Red.fastq.gz
Obviously, an extra Reads_ was appended to the folder specification.
I changed this to a single "Reads_" with
sed -i.bak 's/Reads_Reads_/Reads_/' sorted_files.txt 
But would be good to change in code.

**Comment by atifrahman** [comment]
Thanks! Will do.
