### ISSUE TITLE
runHAWK ends with 'file doesn't exist' issue

### ISSUE THREAD

**Issue by droeatumn** [atifrahman/HAWK#17]
runHAWK, sorted_files.txt, total_kmer_counts.txt, and gwas_info.txt are in the same directory. gwas_info.txt contains
```
Hyp38749	M	Control
Hyp38750	M	Control
Hyp38760	F	Case
Hyp38874	F	Case
Hyp38883	F	Case
```
When I execute './runHAWK', is seg faults on '/home/roex0050/bin/HAWK-0.9.8-beta/hawk 3 2' with the message
```
Hyp38760 file doesn't exist
F file doesn't exist
Case file doesn't exist
```
I am running the 0.9.8 beta release on Ubuntu 18.04.4 LTS.
Did I configure something wrong maybe?

**Comment by atifrahman** [comment]
Can you check whether sorted_files.txt contains all the file names correctly?

**Comment by droeatumn** [comment]
Originally, it had an extra 'Reads_' in the names of the two Reads* directories. I changed that, and made sure the two lines in sorted_files.txt correctly pointed to the 'kmers_sorted.txt' files. However, when I rerun, the exact same thing happens.

**Comment by droeatumn** [comment]
Should I attach some logs and other files? I can provide the larger files too; there are no privacy, etc. issues.

**Comment by atifrahman** [comment]
Can you please attach sorted_files.txt, total_kmer_counts.txt, and gwas_info.txt for now?

**Comment by droeatumn** [comment]
[total_kmer_counts.txt](https://github.com/atifrahman/HAWK/files/4357047/total_kmer_counts.txt)
[sorted_files.txt](https://github.com/atifrahman/HAWK/files/4357048/sorted_files.txt)
[gwas_info.txt](https://github.com/atifrahman/HAWK/files/4357049/gwas_info.txt)

**Comment by droeatumn** [comment]
This is the original sorted_files.txt. I removed an extra 'Reads_'.

[sorted_files.txt](https://github.com/atifrahman/HAWK/files/4357208/sorted_files.txt)

**Comment by atifrahman** [comment]
Can you please try again using the new version?

**Comment by droeatumn** [comment]
This is what I get with 0.9.9:
```
$ ./runHawk 
Hyp38760 file doesn't exist
F file doesn't exist
Case file doesn't exist
./runHawk: line 17:  9551 Segmentation fault      $hawkDir/hawk $caseCount $controlCount
```

$caseCount is 3 and $controlCount is 2

**Comment by atifrahman** [comment]
0.9.9 is actually the version before the updates. Could you please try 1.5.0? Sorry about the confusion

**Comment by droeatumn** [comment]
I get the same thing on 1.5.0
```
./runHawk
./runHawk: line 22: 24461 Segmentation fault      $hawkDir/hawk.out $caseCount $controlCount > hawk_out.txt
```
and hawk_out.txt is 
```
Hyp38760 file doesn't exist
F file doesn't exist
Case file doesn't exist
```

I doubled checked the accuracy of the files in sorted_files.txt. Those files are in a sub dir from where I execute runHawk.

**Comment by atifrahman** [comment]
Are the total_kmer_counts.txt, sorted_files.txt and gwas_info.txt files that shared complete? Each has different number of entries.

**Comment by droeatumn** [comment]
I'm trying to start from scratch with 1.5.0 beta. It appears countKmers_jf1 and countKmers_jf2 no longer look for fastqs in Reads folders. They now use the contents of links.txt files and expect the data to be in sra format. Is this intentional? It isn't consistent with the README. Should I use countKmers_old?

**Comment by atifrahman** [comment]
Yeah... whichever script for counting is best suited for you. As long as the total_kmer_counts.txt, sorted_files.txt and gwas_info.txt files are correct, the later steps should work

**Comment by droeatumn** [comment]
Thanks for the hint. It helped me figure out the correct layout of the input fastq files. I have it running now.
