### ISSUE TITLE
segmentation fault with preProcess.out

### ISSUE THREAD

**Issue by phil-grayson** [atifrahman/HAWK#21]
Hi, 

I `git clone`'d the most recent HAWK repository (1.5.0 BETA) and I was able to get the modified version of jellyfish installed and run for my samples.  I am at the `runHawk` step and after copying and modifying that script to my scratch space and carrying out `make` in the main HAWK directory, I have tried to run it as described in the readme file.  I am consistently getting an error almost immediately:

`./runHawk: line 15: 63826 Segmentation fault      (core dumped) $hawkDir/preProcess.out`

The number after `line 15` changes, but the Segmentation fault always occurs at this step.  The program will continue running and starts to work on the `hawk.out` step given what I'm seeing in htop, but I wanted to see if the preProcess error can be fixed (or if it should be ignored since the program continues to run)?

Thanks!

**Comment by atifrahman** [comment]
Would you be able to share the following files?
sorted_files.txt
total_kmer_counts.txt
gwas_info.txt
case_sorted_files.txt
case_total_kmers.txt
case.ind
control_sorted_files.txt
control_total_kmers.txt
control.ind

**Comment by phil-grayson** [comment]
Thanks for the quick reply.  It looks like my test run (leaving it running) has already finished (but it has more errors).  Here's the stderr/stdout:
```
./runHawk: line 15:  6704 Segmentation fault      (core dumped) $hawkDir/preProcess.out
fatalx:
no snps found: snpfname: gwas_eigenstratX.snp
./runHawk: line 31: 58879 Aborted                 (core dumped) $eigenstratDir/bin/smartpca -p $hawkDir/parfile.txt > log_eigen.txt
./runHawk: line 53: 58940 Segmentation fault      (core dumped) $hawkDir/log_reg_case.out -t $noThread $sex_confounder_arg -p $noPC > pvals_case_top.txt
./runHawk: line 53: 58944 Segmentation fault      (core dumped) $hawkDir/log_reg_control.out -t $noThread $sex_confounder_arg -p $noPC > pvals_control_top.txt
```

I've attached my sorted_files.txt, total_kmer_counts.txt, and gwas_info.txt. The case and control files all have size 0.  
[sorted_files.txt](https://github.com/atifrahman/HAWK/files/5151195/sorted_files.txt)
[gwas_info.txt](https://github.com/atifrahman/HAWK/files/5151196/gwas_info.txt)
[total_kmer_counts.txt](https://github.com/atifrahman/HAWK/files/5151197/total_kmer_counts.txt)

**Comment by atifrahman** [comment]
There is an extra newline at the end of gwas_info.txt which is causing trouble. I thought the files would be written to even if that caused an error at the end. This was sloppy on our part and sorry about that!

Can you please remove it and try again for now? We'll fix it later.

**Comment by phil-grayson** [comment]
Ah, yes.  Sorry about the extra newline!  It's running now.  No segment fault was generated and it is running the `hawk.out` step again.  All of the other files you requested now have something in them!  Thanks!

**Comment by phil-grayson** [comment]
My run seems to have finished with no errors, but both my case_kmers.fasta and control_kmers.fasta files are empty.  Looking at `ls -l`, they were the most recent files to be created.  Just before that, pvals_control_top_merged_sorted.txt and pvals_case_top_merged_sorted.txt were generated with over 50 million lines each (according to `wc -l`).  `head` of those files shows pvals around 1.xe-6 (in column 1, which appears to be the sorted one).  Column 5 also has values that look like they could be pvals, but they are unsorted and range from e-12 to e-18 in the `head` of both files.  Was there a problem generating the case and control fasta files or are my pvalues not good enough to warrant any k-mers in those lists?  Thanks!

**Comment by atifrahman** [comment]
That's probably because none of the k-mers passed the Bonferroni threshold after correcting for confounders. Column 1 is p-values after confounder correction and Column 5 is p-values before that. You can try running Benjamini-Hochberg procedure
https://github.com/atifrahman/HAWK/blob/master/supplements/runBHCorrection
If that doesn't result in anything, then one approach may be to investigate the k-mers with smallest p-values to see if they provide any insights (hits to candidate genes, etc).

**Comment by phil-grayson** [comment]
Thanks!  I ran the BHCorrection. It took only a couple minutes and generated two additional empty files: case_kmers_bh_correction.fasta and control_kmers_bh_correction.fasta.  I'll probably try to dig into the kmers with the smallest p-values at this point and see if that gets me anywhere.  Can you provide me some additional information on the columns of the pvals_case_top_merged_sorted.txt file (and its control partner)?  Column 1 is corrected p-values, column 2 looks to be the sequence, then column 3 and 4 have numbers, 5 has uncorrected p-values and the rest of the columns (for me it's another 20 columns) have numbers.  I had 20 samples, so I'm assuming that these 20 columns are counts across my inputs? what is the order of these columns?  also, what are columns 3 and 4 (they look close to a tally of the counts from the other columns, but not quite - maybe corrected in some way)?  finally, if I want to generate input for abyss, what would a successful case_kmers.fasta file contain so that I can make a fake one from these data?  Thanks again :)

**Comment by phil-grayson** [comment]
Just wanted to give this a bump. Would be really excited to get this clarification.  Thanks!

**Comment by atifrahman** [comment]
Sorry... missed the earlier comment.

Column 3 is the sum of the counts of case samples. Column 4 is the sum of the counts of the control samples, scaled to the total number of k-mers in cases i.e. sum_of_Control_counts*total_no_Kmers_Cases/total_no_Kmers_Controls

The last ones are the counts in input samples as you guessed. The order is all the case samples followed by all the control samples, where the case and control samples are in the same order as in the file gwas_info.txt

**Comment by phil-grayson** [comment]
Excellent! Thanks 👍  That's very helpful.

I think the last thing I would like to try is put my top sets of case and control k-mers through to abyss.  Let's say that I want to take the top 1000 in each case and see if they assemble into anything.  Can you tell me what would a successful case_kmers.fasta (or control_kmers.fasta) file contains (which columns and what order) so that I can make them from the pvals files? I think I can close out this thread after that!

**Comment by atifrahman** [comment]
This is what the fasta files look like
>7.811470e-21
AAGATCCTTGAGAGTTTTCGCCCCGAAGAAC
>7.814280e-21
AAAACGTTCTTCGGGGCGAAAACTCTCAAGG
>7.863070e-21
CTTGAGAGTTTTCGCCCCGAAGAACGTTTTC

We've used the p-values as sequence IDs in the standard fasta format (https://en.wikipedia.org/wiki/FASTA_format) for convenience.

**Comment by phil-grayson** [comment]
awesome!  thanks so much for all the clarification!
