### ISSUE TITLE
runHawk fasta files for cases and controls have number not fasta sequence in them 

### ISSUE THREAD

**Issue by robertwhbaldwin** [atifrahman/HAWK#25]
I ran runHawk and the output fasta (below) was not a fasta file. There's numbers where there should be strings. Is this supposed to look like this?

>0.000000e+00
65
>0.000000e+00
47
>0.000000e+00
36
>0.000000e+00
40
>0.000000e+00
47
>0.000000e+00
787
>0.000000e+00
45
>0.000000e+00
36
>0.000000e+00
89
>0.000000e+00
49
>0.000000e+00
813
>0.000000e+00
43
>0.000000e+00
39

**Comment by callmeviny** [comment]
I am running in the same issue. Any pointers?
